// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckEnvironment():Promise<void>;

export function CheckUpdate(arg1:string):Promise<main.UpdateResult>;

export function GetUserHomeDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LaunchClaude(arg1:boolean,arg2:string):Promise<void>;

export function LoadConfig():Promise<main.AppConfig>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectProjectDir():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;
